[package]
authors = ["Guil. Sperb Machado <guil@axlabs.com>"]
name = "tfhe-gps-distance"
version = "0.1.0"
edition = "2024"

[dependencies]
tfhe = { version = "1.1.1", features = ["boolean", "shortint", "integer"]}